#
# This file is autogenerated during plugin quickstart and overwritten during
# plugin makedist. DO NOT CHANGE IT if you plan to use plugin makedist to update 
# the distribution.
#

from setuptools import setup, find_packages

kwargs = {'author': '',
 'author_email': '',
 'classifiers': ['Intended Audience :: Science/Research',
                 'Topic :: Scientific/Engineering'],
 'description': '',
 'download_url': '',
 'entry_points': '[openmdao.component]\nnreltraining2013.nreltraining2013.BEMPerf=nreltraining2013.nreltraining2013:BEMPerf\nnreltraining2013.nreltraining2013.ActuatorDisk=nreltraining2013.nreltraining2013:ActuatorDisk\nnreltraining2013.nreltraining2013.BEM=nreltraining2013.nreltraining2013:BEM\nnreltraining2013.nreltraining2013.BladeElement=nreltraining2013.nreltraining2013:BladeElement\nnreltraining2013.nreltraining2013.AutoBEM=nreltraining2013.nreltraining2013:AutoBEM\n\n[openmdao.container]\nnreltraining2013.nreltraining2013.BEMPerfData=nreltraining2013.nreltraining2013:BEMPerfData\nnreltraining2013.nreltraining2013.BEMPerf=nreltraining2013.nreltraining2013:BEMPerf\nnreltraining2013.nreltraining2013.ActuatorDisk=nreltraining2013.nreltraining2013:ActuatorDisk\nnreltraining2013.nreltraining2013.FlowConditions=nreltraining2013.nreltraining2013:FlowConditions\nnreltraining2013.nreltraining2013.BladeElement=nreltraining2013.nreltraining2013:BladeElement\nnreltraining2013.nreltraining2013.AutoBEM=nreltraining2013.nreltraining2013:AutoBEM\nnreltraining2013.nreltraining2013.BEM=nreltraining2013.nreltraining2013:BEM',
 'include_package_data': True,
 'install_requires': ['openmdao.main'],
 'keywords': ['openmdao'],
 'license': '',
 'maintainer': '',
 'maintainer_email': '',
 'name': 'nreltraining2013',
 'package_data': {'nreltraining2013': []},
 'package_dir': {'': 'src'},
 'packages': ['nreltraining2013'],
 'url': '',
 'version': '1.5',
 'zip_safe': False}


setup(**kwargs)

